# Generated by Django 5.1.6 on 2025-02-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=1000)),
                ('project_summary', models.CharField(max_length=100)),
                ('project_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
