# Generated by Django 5.1.6 on 2025-02-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
