# Generated by Django 5.1.6 on 2025-02-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_projectdetails_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
