# Generated by Django 5.1.6 on 2025-02-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_projectdetails_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_img',
            field=models.ImageField(blank=True, default='project_images/default.webp', null=True, upload_to='project_images/'),
        ),
    ]
