# Generated by Django 5.1.6 on 2025-02-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_projectdetails_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='project_summary',
            field=models.CharField(max_length=300),
        ),
    ]
